version: "3.7"

services:
  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile.dev
    volumes:
      - ./nestjs/src:/upco/src
    ports:
      - 3000:3000
    env_file:
      - ./.env
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "upco"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - ./.env
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="chat"
    ports:
      - 27017:27017
  api-gateway:
    image: nginx:latest
    volumes:
      - ./gateway/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
