apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          env:
            - name: "MONGODB_CONNECTION"
              valueFrom:
              configMapKeyRef:
                key: "MONGODB_CONNECTION"
                name: "chat-configmap"
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
