apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
