name: Build and Deploy chat to GKE

on:
  pull_request:
    branches:
      - master
    paths:
      - chat/**

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: asia-northeast3
  GKE_CLUSTER: team-project-cluster
  GKE_ZONE: asia-northeast3
  DEPLOYMENT_CHAT_NAME: chat
  IMAGE_CHAT: chat
  MONGODB_CONNECTION: ${{ secrets.MONGODB_CONNECTION }}
  
jobs:
  chat:
    name: Setup, Build, Publish, and Deploy for chat
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          -f "./chat/Dockerfile.prod" \
          --tag "gcr.io/$PROJECT_ID/$IMAGE_CHAT:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE_CHAT:$GITHUB_SHA"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        cd ./chat
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        cd ./chat
        echo MONGODB_CONNECTION=$MONGODB_CONNECTION >> .env
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE_CHAT:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_CHAT_NAME
        kubectl get services -o wide
